// Generates docs/brand/logo.svg: the A1 monogram.
// Two glyphs share one stroke. The 1 (deep tone) is a stem on a base with a
// short flag; the A (light tone) is a long leg and a crossbar that borrow the
// 1's stem as their right side. Flat tones, no gradient, no glow.
import { writeFileSync } from "node:fs";
const W = 58;                            // stroke width
const LIGHT = "#00B877", DEEP = "#007A50";
const TOP = 92, BASE = 392;              // apex line and baseline
const FOOT_H = 30, FOOT_W = 124;         // the 1's base
const stemX = 300;                       // left edge of the stem
const apex = [stemX + W / 2, TOP], foot = [126, BASE];
const FLAG = 0.30;                       // how far down the leg the 1's flag reaches
function band([x1, y1], [x2, y2], w, ext = 60) {
  const dx = x2 - x1, dy = y2 - y1, L = Math.hypot(dx, dy);
  const ux = dx / L, uy = dy / L, nx = -uy * w / 2, ny = ux * w / 2;
  const a = [x1 - ux * ext, y1 - uy * ext], b = [x2 + ux * ext, y2 + uy * ext];
  return [[a[0] + nx, a[1] + ny], [b[0] + nx, b[1] + ny], [b[0] - nx, b[1] - ny], [a[0] - nx, a[1] - ny]]
    .map(p => p.map(v => +v.toFixed(1)).join(",")).join(" ");
}
const flagEnd = [apex[0] + (foot[0] - apex[0]) * FLAG, apex[1] + (foot[1] - apex[1]) * FLAG];
// the flag's lower end is cut square to the leg
const dx = foot[0] - apex[0], dy = foot[1] - apex[1], L = Math.hypot(dx, dy), ux = dx / L, uy = dy / L;
const cutA = [flagEnd[0] - uy * 100, flagEnd[1] + ux * 100], cutB = [flagEnd[0] + uy * 100, flagEnd[1] - ux * 100];
const flagClip = `${cutA.map(v => v.toFixed(1))} ${cutB.map(v => v.toFixed(1))} ${(cutB[0] - ux * 300).toFixed(1)},${(cutB[1] - uy * 300).toFixed(1)} ${(cutA[0] - ux * 300).toFixed(1)},${(cutA[1] - uy * 300).toFixed(1)}`;
const barY = 286, barH = 46;
const t = (barY + barH / 2 - TOP) / (BASE - TOP);
const legCx = apex[0] + dx * t;
const legInner = legCx + (W / 2) / Math.cos(Math.atan2(dx, dy)) - 2;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <!-- A NEW ONE: the A1 monogram. A for A NEW ONE, 1 for the ONE; together, A1.
       Two glyphs share one stroke: the 1 (deep tone) is a stem on a base with a
       short flag; the A (light tone) is a long leg and a crossbar that borrow
       the 1's stem as their right side. Generated by build-brand/a1.mjs. -->
  <defs>
    <clipPath id="leg"><rect x="0" y="${TOP}" width="512" height="${BASE - TOP}"/></clipPath>
    <clipPath id="flag"><polygon points="${flagClip}"/><rect x="0" y="0" width="512" height="${TOP}"/></clipPath>
    <clipPath id="top"><rect x="0" y="${TOP}" width="512" height="512"/></clipPath>
  </defs>
  <!-- A: the leg -->
  <g clip-path="url(#leg)"><polygon points="${band(apex, foot, W)}" fill="${LIGHT}"/></g>
  <!-- A: the crossbar, from the leg to the stem -->
  <rect x="${legInner.toFixed(1)}" y="${barY}" width="${(stemX - legInner + 4).toFixed(1)}" height="${barH}" fill="${LIGHT}"/>
  <!-- 1: the stem, shared with the A -->
  <rect x="${stemX}" y="${TOP}" width="${W}" height="${BASE - TOP}" fill="${DEEP}"/>
  <!-- 1: the base -->
  <rect x="${stemX + W / 2 - FOOT_W / 2}" y="${BASE}" width="${FOOT_W}" height="${FOOT_H}" fill="${DEEP}"/>
  <!-- 1: the flag, laid over the top of the A's leg -->
  <g clip-path="url(#top)"><g clip-path="url(#flag)"><polygon points="${band(apex, foot, W)}" fill="${DEEP}"/></g></g>
</svg>
`;
writeFileSync(new URL("../docs/brand/logo.svg", import.meta.url), svg);
console.log("wrote docs/brand/logo.svg");
