// Generates docs/brand/logo.svg: the ribbon A1 with a network dome.
// The format the client chose: a flowing ribbon A fused with a 1, a wireframe
// dome of nodes rising over it, mint gradients on deep green-black.
import { writeFileSync } from "node:fs";
const R = (v) => +v.toFixed(1);
// ---- ribbon A: curl at the foot, up to a sharp apex, down the right leg
const apex = [500, 238], footL = [300, 770], footR = [700, 782];
const legA = `M215 700 C205 775 275 815 300 770 L${apex} L${footR}`;
// crossbar: a soft wave that sits on both legs
const yOn = (y, a, b) => R(a[0] + (y - a[1]) / (b[1] - a[1]) * (b[0] - a[0]));
const bar = `M${yOn(650, footL, apex)} 650 C410 622 520 662 ${yOn(606, apex, footR)} 606`;
// ---- the 1: a tall stroke leaning with the A, with a flag
const one = `M655 330 L742 236 L772 780`;
// ---- the dome: a wireframe hemisphere with nodes on the crossings
const cx = 455, cy = 655, r = 425;
const dome = [];
const arc = (rx) => `M${cx - rx} ${cy} A${rx} ${r} 0 0 1 ${cx + rx} ${cy}`;
dome.push(arc(r), arc(260), arc(95));
// two parallels: ellipses cut to the upper half
const lat = (h) => { const w = R(Math.sqrt(r * r - h * h)); return `M${cx - w} ${cy - h} A${w} ${R(w * 0.22)} 0 0 1 ${cx + w} ${cy - h}`; };
dome.push(lat(150), lat(300));
// nodes: on the outer arc and at the parallel crossings
const nodes = [];
for (const deg of [8, 30, 55, 80, 105, 128, 152, 172]) {
  const a = (deg * Math.PI) / 180; nodes.push([R(cx - r * Math.cos(a)), R(cy - r * Math.sin(a))]);
}
for (const h of [150, 300]) { const w = Math.sqrt(r * r - h * h);
  for (const rx of [260, 95, -95, -260]) { const t = rx / w; if (Math.abs(t) < 1) nodes.push([R(cx + rx), R(cy - h - w * 0.22 * Math.sqrt(1 - t * t) * 1)]); } }
// background constellation, faint
const bg = [[60, 120], [150, 60], [230, 150], [110, 260], [900, 90], [960, 200], [850, 230], [980, 330], [80, 880], [170, 950], [940, 900], [880, 980]];
const bgLines = [[0, 1], [1, 2], [0, 3], [2, 3], [4, 5], [5, 6], [4, 6], [5, 7], [8, 9], [10, 11]];
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- A NEW ONE: the ribbon A1 under a network dome. Generated by build-brand/ribbon.mjs. -->
  <defs>
    <radialGradient id="ground" cx="50%" cy="45%" r="70%">
      <stop offset="0" stop-color="#0b2b21"/><stop offset="1" stop-color="#04100c"/>
    </radialGradient>
    <linearGradient id="ribbon" x1="200" y1="240" x2="720" y2="800" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#9DFFD9"/><stop offset=".45" stop-color="#2FE39A"/><stop offset="1" stop-color="#0B8F5C"/>
    </linearGradient>
    <linearGradient id="ribbonEdge" x1="200" y1="240" x2="720" y2="800" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0E7A50"/><stop offset="1" stop-color="#064A32"/>
    </linearGradient>
    <linearGradient id="oneFill" x1="650" y1="230" x2="780" y2="780" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#EAFFF6"/><stop offset=".5" stop-color="#9CF5CF"/><stop offset="1" stop-color="#2FBF85"/>
    </linearGradient>
    <linearGradient id="oneEdge" x1="650" y1="230" x2="780" y2="780" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#3FB98A"/><stop offset="1" stop-color="#0F6B48"/>
    </linearGradient>
    <linearGradient id="wire" x1="0" y1="230" x2="0" y2="655" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#A8FFE0"/><stop offset="1" stop-color="#1F9F6E" stop-opacity=".6"/>
    </linearGradient>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="16"/></filter>
    <filter id="nodeGlow" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="5"/></filter>
    <clipPath id="upper"><rect x="0" y="0" width="1024" height="${cy}"/></clipPath>
  </defs>
  <rect width="1024" height="1024" fill="url(#ground)"/>
  <!-- background constellation -->
  <g stroke="#2FBF85" stroke-opacity=".18" stroke-width="2">
    ${bgLines.map(([a, b]) => `<line x1="${bg[a][0]}" y1="${bg[a][1]}" x2="${bg[b][0]}" y2="${bg[b][1]}"/>`).join("\n    ")}
  </g>
  <g fill="#9CF5CF" fill-opacity=".35">
    ${bg.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="4"/>`).join("\n    ")}
  </g>
  <!-- the dome -->
  <g clip-path="url(#upper)" fill="none" stroke="url(#wire)" stroke-width="3.5" stroke-linecap="round">
    ${dome.map((d) => `<path d="${d}"/>`).join("\n    ")}
  </g>
  <g fill="#B2FFE4" filter="url(#nodeGlow)" opacity=".9">
    ${nodes.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="9"/>`).join("\n    ")}
  </g>
  <g fill="#EFFFF8">
    ${nodes.map(([x, y]) => `<circle cx="${x}" cy="${y}" r="6"/>`).join("\n    ")}
  </g>
  <!-- glow under the letters -->
  <g fill="none" stroke="#2FE39A" stroke-opacity=".45" stroke-width="80" stroke-linejoin="miter" stroke-miterlimit="3" filter="url(#glow)">
    <path d="${legA}"/><path d="${one}"/>
  </g>
  <!-- the 1, behind the A -->
  <g fill="none" stroke-width="66" stroke-linejoin="miter" stroke-miterlimit="3" stroke-linecap="butt">
    <path d="${one}" stroke="url(#oneEdge)" transform="translate(12 12)"/>
    <path d="${one}" stroke="url(#oneFill)"/>
  </g>
  <!-- the ribbon A -->
  <g fill="none" stroke-width="64" stroke-linejoin="miter" stroke-miterlimit="3" stroke-linecap="butt">
    <path d="${legA}" stroke="url(#ribbonEdge)" transform="translate(12 12)"/>
    <path d="${bar}" stroke="url(#ribbonEdge)" stroke-width="44" transform="translate(10 10)" stroke-linecap="round"/>
    <path d="${legA}" stroke="url(#ribbon)"/>
    <path d="${bar}" stroke="url(#ribbon)" stroke-width="44" stroke-linecap="round"/>
  </g>
  <!-- a highlight along the ribbon's crest -->
  <g fill="none" stroke="#FFFFFF" stroke-opacity=".35" stroke-width="8" stroke-linecap="round">
    <path d="M318 738 L${apex[0] - 6} ${apex[1] + 30}"/>
    <path d="M756 262 L778 690"/>
  </g>
</svg>
`;
writeFileSync(new URL("../docs/brand/logo.svg", import.meta.url), svg);
console.log("wrote docs/brand/logo.svg");
